

services:
    postgres:
        image: postgres
        container_name: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD : admin
            POSTGRES_dB: car_sales_db
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports :
            - "5432:5432"
        networks:
            - webapi_network
        restart: unless-stopped 

    pgadmin :
        image: dpage/pgadmin4
        container_name: pdadmin_container
        environment :
            PGADMIN_DEFAULT_EMAIL: v.lotfi71@gmail.com
            PGADMIN_DEFAULT_PASSWORD: 1234567
        volumes:
            - pgadmin:/var/lib/pgadmin
        ports:
            - "8090:80"
        networks:
            - webapi_network
        restart: unless-stopped
        depends_on:
                - postgres
    
    redis:
        image: redis:latest
        container_name: redis_container
        command: ["redis-server","/ext/redis/redis.conf"]
        volumes:
          - ./redis/redis.conf:/ext/redis/redis.conf
          - redis:/ext/redis.conf
          - redis:/data
        ports:
          - "6379:6379"
        networks:
            - webapi_network    
          






volumes : 
    postgres:
    pgadmin:
    redis:
    logs:

networks:
  webapi_network:
     driver: bridge
